<!DOCTYPE html>
<html lang="en">
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title><?=(isset($App->view->title)? $App->view->title:'')?></title>
	
	<?if (!empty($App->view->description)):?><meta name="description" content="<?=$App->view->description?>"><?endif?>
	
	<?=$App->view->cssoutput?>
	
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1">

	<?if (!empty($App->view->title)):?>
	<meta property="og:title" content="<?=$App->view->title?>">
	<?endif?>

	<?if ($App->view->ogPageType !== false):?>
	<meta property="og:type" content="<?=$App->view->ogPageType?>">
	<?else:?>
	<meta property="og:type" content="website">
	<?endif?>
	
	<?if ($App->view->ogImage !== false):?>
	<meta property="og:image" content="<?=$App->view->ogImage?>">
	<?endif?>

	<?if (!empty($App->view->description)):?>
	<meta property="og:description" content="<?=$App->view->description?>">
	<?endif?>

	<meta property="og:url" content="<?=$App->request->url->full?>">

	<?=$App->view->headHtml?>
</head>

<body class="index">
	<?$App->displayErrors();?>
	<?=$App->view->html?>

	<footer>
		© <?=date("Y")?> <?=$App->config->site->title?>
		
	</footer>
	
	<script>
	
	</script>

	<!--[if lt IE 11]>
		<script src="https://raw.githubusercontent.com/jonathantneal/flexibility/master/flexibility.js"></script>
	<![endif]-->	

	<?=$App->view->jsoutput?>
	
</body>
</html>