<!DOCTYPE html>
<html lang="en">
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title><?=(isset($_metaTitle)? $_metaTitle:'')?></title>
	
	<?if(!empty($_metaDescription)):?><meta name="description" content="<?=$_metaDescription?>"><?endif?>
	
	<?=$_css?>
	
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1">

	<?if(!empty($_metaTitle)):?>
	<meta property="og:title" content="<?=$_metaTitle?>">
	<?endif?>

	<?if(isset($App->view->ogPageType)):?>
	<meta property="og:type" content="<?=$App->view->ogPageType?>">
	<?else:?>
	<meta property="og:type" content="website">
	<?endif?>

	<?if(isset($App->view->ogImage)):?>
	<meta property="og:image" content="<?=$App->view->ogImage?>">
	<?endif?>

	<?if(!empty($_metaDescription)):?>
	<meta property="og:description" content="<?=$_metaDescription?>">
	<?endif?>

	<meta property="og:url" content="<?=$request->url?>">
</head>

<body class="index">
	<?$App->displayErrors();?>
	<?=$_html?>

	<footer>
		© <?=date("Y")?> <?=$config->site->title?>
		
	</footer>
	
	<script>
	
	</script>

	<!--[if lt IE 11]>
		<script src="https://raw.githubusercontent.com/jonathantneal/flexibility/master/flexibility.js"></script>
	<![endif]-->	

	<?=$_js?>
	
</body>
</html>