title="Title tag text"
description="Meta description tag text"
{endmeta}
    <header>
		{partial:header.phtml}   
    </header>

	<main style="text-align:center; margin-top:50px">
		<img src="https://raw.githubusercontent.com/truecastdesign/true/master/assets/TrueFramework.png" alt="TrueFramework">
	</main>

	<section style="margin-top:100px">
		<p class="c">Welcome to TrueFramework!</p>
	</section>
	